AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cf-templates-c2wr3vvvtnjz-us-east-1/772080f702f1d41ae0550bb2d377ce39.template
  AutoscalingFront:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - VPCStack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cf-templates-c2wr3vvvtnjz-us-east-1/642668551da64ccf8a08b7d9608a14f8.template
      Parameters:
        Subnets:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnets
